# Shell
shell /home/linuxbrew/.linuxbrew/bin/zsh

# Font
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size        13

# Automatically copy selected text to clipboard
copy_on_select clipboard

# Paste from clipboard
map ctrl+v        paste_from_clipboard


# BEGIN_KITTY_THEME
# Default
include current-theme.conf
# END_KITTY_THEME